CREATE TABLE `ROLLINGSTONE_CART` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CART_TOTAL` double NOT NULL,
  `CART_DATE` date NOT NULL,
  `user_profile_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_USER_ID` FOREIGN KEY (`user_profile_id`) REFERENCES `rollingstone_user` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

CREATE TABLE `ROLLINGSTONE_CART_ITEM` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `OFFER_ID` bigint(20) NOT NULL,
   `PRODUCT_ID` bigint(20) NOT NULL,
   `QUANTITY` bigint(20) NOT NULL,
    `UNIT` varchar(255) NOT NULL,
	`PRICE` double NOT NULL,
	`FFM_TYPE` varchar(255) NOT NULL,
	`CART_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_CART_ID` FOREIGN KEY (`CART_ID`) REFERENCES `ROLLINGSTONE_CART` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;